import { Roboto, Roboto_Condensed, Roboto_Mono, Roboto_Slab } from 'next/font/google'
import './globals.css'

const robotoSans = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin']
})

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin']
})

const robotoCondensed = Roboto_Condensed({
  variable: '--font-roboto-condensed',
  subsets: ['latin']
})

const robotoSlab = Roboto_Slab({
  variable: '--font-roboto-slab',
  subsets: ['latin']
})

export const metadata = {
  title: 'Gundam FFS',
  description: 'Generated by create next app',
  icons: 'favicon.png'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
      className={`${robotoSans.variable} ${robotoMono.variable} ${robotoCondensed.variable} ${robotoSlab.variable}  antialiased`}>
    {children}
    </body>
    </html>
  )
}
